config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :enrollments
  resources :instituions
  resources :students


  get 'students/', to: "posts#index"
  root to: "students#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :enrollment

  #Validation
  validates :invoice_amount, :due_data, :status, presence: true
  after_initialize :init_status, if: :new_record?
  validates_inclusion_of :status, in: [ "atrasada","paga","aberta" ]
  
  def init_status
    self.status ||= "aberta" 
  end


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:invoice_amount, :due_data, :status, :enrollment_id)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this test from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= @invoice.errors.full_messages.first if @invoice.errors.any? %>
    <div class="d-flex justify-content-center row g-3">
      <div class="col-md-7 col-lg-8">
        <div class="row g-3">
                  <div class="form-check col-md-12">
                        <label class="form-label">Valor da Parcela:</label>
                        <br>
                  <%= form.text_field :invoice_amount   ,class:"form-control"%><br>
                  </div>
        </div>
        <div class="row g-3">
            <div class="form-check col-md-10">
                  <label class="form-label">Dia de Vencimento:</label>
                  <br>
                  <%= form.date_select :due_data, :order => [:day, :month, :year], class:"input-mini", start_year: 1922%><br>
            </div>
            <div class="col-md-2">
                  <label class="form-label">status:</label>
                  <br>
                  <%= form.select :status , ['aberta', 'paga'], class:"input-mini"%>
            </div>

        </div>
            <%= form.submit "Enviar" , class:"btn btn-dark enviar actions"%>
        <% end %>
      </div>
  </div>
 

app/views/invoices/edit.html.erb
<h1 class="center bd-danger">Editar Boleto</h1>
<%= render 'form', invoice: @invoice %>

app/views/invoices/index.html.erb
<h1 class="text-center mt-5 mb-5">Dados do Boleto</h1>

<table class="table table-striped mx-auto w-75 table-active border border-dark" >
  <thead>
    <tr class="dark">
       <th class="text-center">Invoice amount</th>
       <th class="text-center">Due data</th>
       <th class="text-center">Status</th>
       <th class="text-center">Enrollment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
           <tr>
        <td class="text-center"><%= invoice.invoice_amount %></td>
        <td class="text-center"><%= invoice.due_data %></td>
        <td class="text-center"><%= invoice.status %></td>
        <td class="text-center"><%= invoice.enrollment_id %></td>
        <td class="text-center"><%= link_to 'Show', invoice %></td>
        <td class="text-center"><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td class="text-center"><%= button_to 'Delete', invoice_path(invoice), method: :delete, data: {confirm: "Are you sure?"} , class: "delete"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-dark voltar"><%= link_to 'Criar um novo Boleto', new_student_path %></button>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<div class="container" >
      <div class="pt-10 mx-auto align-middle shadow show" style="width: 500px;">
        <h1 class="mb-5 ">Dados do Boleto</h1>
        <section class="grid">
          <div><p class="var">Valor da Parcela:</p></div>
          <div><p class="info"><%= @invoice.invoice_amount %></p></div>
          <div><p class="var">Data de Vencimento:</p></div>
          <div><p class="info"><%= @invoice.due_data %></p></div>
          <div><p class="var">Status do Boleto:</p></div>
          <div><p class="info"><%= @invoice.status %></p></div>
          <div><p class="var">ID da Matrícula:</p></div>
          <div><p class="info"><%= @invoice.enrollment_id %></p></div>
        </section>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Editar', edit_invoice_path(@invoice) %></button>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Voltar', invoices_path %></button>
      </div>
</div>