config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :enrollments
  resources :instituions
  resources :students


  get 'students/', to: "posts#index"
  root to: "students#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    require "cpf_cnpj"
    has_many :enrollments, dependent: :destroy
    #validation
    validates :name, :cpf, :gender, :payment_method, presence: true
    validates :name, uniqueness: true 
    validates :cpf, uniqueness: true 
    validates :cpf, :cellphone, length: {is: 11}, numericality: {only_integer: true}
    #Utilizando Regex
    #VALIDATE_CPF =/[0~9]/
    #validates :cpf , format: {with: VALIDATE_CPF, message:"Insira apenas números"}
    validates :gender, inclusion: { in: %w(Feminino Masculino),
        message: "Não é uma entrada aceita para genêro" }
    validates :payment_method, inclusion: { in: %w(Boleto Cartao),
        message: "Escolha uma forma de pagamento :Cartao ou Boleto" }    
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include Paginable

  before_action :set_student, only: %i[ show edit update destroy delete]

  # GET /students or /students.json
  def index
    @students = Student.page(current_page).per(per_page)

  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to students_path, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    if @student.update(student_params)
      respond_to do |format|
        format.html { redirect_to students_path, notice: 'Student was successfully destroyed.' }
      end
    else
      render json: @student.errors, status: 422
    end
  end


  # DELETE /students/1 or /students/1.json

  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_path, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :cpf, :gender, :payment_method, :birth_date, :cellphone)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this test from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= @student.errors.full_messages.first if @student.errors.any? %>
    <div class="d-flex justify-content-center row g-3">
      <div class="col-md-7 col-lg-8">
      <div class="form-check col-12">
            <label class="form-label">Nome:</label>
        <%= form.text_field :name  ,class:"form-control"%><br>
      </div>

        <div class="form-check col-12">
            <label class="form-label">CPF:</label>
            <%= form.text_field :cpf  ,class:"form-control"%><br>
        </div>

      <div class="form-check col-12 field">
            <label class="form-label">Telefone:</label>
        <%= form.text_field :cellphone  ,class:"form-control"%><br>
      </div>

<div class="row g-3">
      <div class="form-check col-md-6">
            <label class="form-label">Data de Nascimento:</label>
            <br>
        <%= form.date_select :birth_date, :order => [:day, :month, :year], class:"input-mini", start_year: 1922%><br>
      </div>

      <div class="col-md-3">
              <label class="form-label">Genêro:</label>
              <br>
                 <%= form.select :gender, ['Masculino', 'Feminino'], class:"input-mini"%>
            </div>

            <div class="col-md-3">
              <label class="form-label">Metódo de Pagamento:</label>
              <br>
                 <%= form.select :payment_method, ['Cartao', 'Boleto'], class:"input-mini"%>
            </div>

      </div>
            <%= form.submit "Enviar" , class:"btn btn-dark enviar actions"%>
        <% end %>
    
     </div>



</div>

app/views/students/edit.html.erb
<h1 class="center bd-danger">Editar Estudante</h1>
<%= render 'form', student: @student %>

app/views/students/index.html.erb
<h1 class="text-center mt-5 mb-5">Estudante</h1>

<table class="table table-striped mx-auto w-75 table-active border border-dark" >
  <thead>
    <tr class="dark">
      <th class="text-center">Nome</th>
      <th class="text-center">CPF</th>
      <th class="text-center">Data de Nascimento</th>
      <th class="text-center">Celular</th>
      <th class="text-center">Genêro</th>
      <th class="text-center">Metodo de pagagmento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td class="text-center"><%= student.cpf %></td>
        <td class="text-center"><%= student.name %></td>
        <td class="text-center"><%= student.birth_date %></td>
        <td class="text-center"><%= student.cellphone %></td>
        <td class="text-center"><%= student.gender %></td>
        <td class="text-center"><%= student.payment_method %></td>
        <td class="text-center"><%= link_to 'Show', student %></td>
        <td class="text-center"><%= link_to 'Edit', edit_student_path(student) %></td>
        <td class="text-center"><%= button_to 'Delete', student_path(student), method: :delete, data: {confirm: "Are you sure?"} , class: "delete"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-dark voltar"><%= link_to 'Criar um novo Estudante', new_student_path %></button>

app/views/students/new.html.erb
<h1 class="center">Novo Estudante</h1>

<%= render 'form', student: @student %>

app/views/students/show.html.erb
<div class="container" >
      <div class="pt-10 mx-auto align-middle shadow show" style="width: 500px;">
        <h1 class="mb-5 ">Dados do Aluno</h1>
        <section class="grid">
          <div><p class="var">Name:</p></div>
          <div><p class="info"><%= @student.name %></p></div>
          <div><p class="var">CPF:</p></div>
          <div><p class="info"><%= @student.cpf %></p></div>
          <div><p class="var">Celular:</p></div>
          <div><p class="info"><%= @student.cellphone %></p></div>
          <div><p class="var">Data de Nascimento:</p></div>
          <div><p class="info"><%= @student.birth_date %></p></div>
          <div><p class="var">Genêro:</p></div>
          <div><p class="info"><%= @student.gender %></p></div>
          <div><p class="var">Metódo de Pagamento:</p></div>
          <div><p class="info"><%= @student.payment_method %></p></div>
        </section>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Editar', edit_student_path(@student) %></button>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Voltar', students_path %></button>
      </div>
</div>