config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :enrollments
  resources :instituions
  resources :students


  get 'students/', to: "posts#index"
  root to: "students#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  require 'date'

  belongs_to :student
  belongs_to :instituion
  has_many :invoices, dependent: :destroy
  after_create :create_invoice
  after_update :after_update_enrollment

  #Validation
  validates :total_course_fee, :number_invoice, :expiration_day, :name_course, presence: true
  validate :total_course_fee_more_than_0
  validate :number_invoice_more_than_0
  validate :expiration_day_between_1_31




  def total_course_fee_more_than_0
    if total_course_fee <= 0 
      errors.add(:total_course_fee, "Precisar ser maior que 0 o valor do curso")
    end
  end

  def number_invoice_more_than_0
    if number_invoice <= 0 
      errors.add(:number_invoice, "Precisar ser maior que 0 o valor do curso")
    end
  end

  def expiration_day_between_1_31
    if number_invoice <= 0 || number_invoice >= 31
      errors.add(:expiration_day, "Precisar ser maior que 0 o valor do curso")
    end
  end
  
  def create_invoice
      UseCaseInvoice.perform(self.total_course_fee, self.number_invoice, self.expiration_day, self)
  end

  def after_update_enrollment
    UseCaseInvoice.perform(self.total_course_fee, self.number_invoice, self.expiration_day, self)
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.new(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:total_course_fee, :number_invoice, :expiration_day, :name_course, :student_id, :instituion_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
     <div id="error_explanation">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this test from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= @enrollment.errors.full_messages.first if @enrollment.errors.any? %>
    <div class="d-flex justify-content-center row g-3">
      <div class="col-md-7 col-lg-8">
  <div class="row g-3">
            <div class="form-check col-md-4">
                  <label class="form-label">Valor Total:</label>
                  <br>
            <%= form.text_field :total_course_fee   ,class:"form-control"%><br>
            </div>
            <div class="col-md-4">
              <label class="form-label">Número de Parcelas:</label>
              <br>
              <%= form.text_field :number_invoice   ,class:"form-control"%><br>
            </div>

            <div class="col-md-4">
              <label class="form-label">Data de Vencimento:</label>
              <br>
              <%= form.text_field :expiration_day   ,class:"form-control"%><br>
            </div>

  </div>
  <div class="row g-3">
            <div class="form-check col-md-6">
                  <label class="form-label">Nome do Curso:</label>
                  <br>
            <%= form.text_field :name_course   ,class:"form-control"%><br>
            </div>
            <div class="col-md-3">
              <label class="form-label">CPF do Estudante:</label>
              <br>
              <%= form.collection_select :student_id, Student.order(:id), :id, :cpf, class:"input-mini"%>
            </div>
       

            <div class="col-md-3">
              <label class="form-label">Nome da Instituição:</label>
              <br>
              <%= form.collection_select :instituion_id, Instituion.order(:id), :id, :name %>
            </div>

  </div>
            <%= form.submit "Enviar" , class:"btn btn-dark enviar actions"%>
        <% end %>
    
</div>
 

app/views/enrollments/edit.html.erb
<h1 class="center bd-danger">Editar Matrícula</h1>
<%= render 'form', enrollment: @enrollment %>

app/views/enrollments/index.html.erb
<h1 class="text-center mt-5 mb-5">Matrículas</h1>

<table class="table table-striped mx-auto w-75 table-active border border-dark" >
  <thead>
    <tr class="dark">
      <th class="text-center">Valor Total</th>
      <th class="text-center">Numero de parcelas</th>
      <th class="text-center">Data de Vencimento</th>
      <th class="text-center">Nome do Curso</th>
      <th class="text-center">Nome da Instituição</th>
      <th class="text-center">Nome do Estudante</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  
    <% @enrollments.each do |enrollment| %>
      <tr>
        <td class="text-center"><%= enrollment.total_course_fee %></td>
        <td class="text-center"><%= enrollment.number_invoice %></td>
        <td class="text-center"><%= enrollment.expiration_day %></td>
        <td class="text-center"><%= enrollment.name_course %></td>
        <td class="text-center"><%= enrollment.student.name %></td>
        <td class="text-center"><%= enrollment.instituion.name %></td>
        <td class="text-center"><%= link_to 'Show', enrollment %></td>
        <td class="text-center"><%= link_to 'Edit', edit_enrollment_path(enrollment) %></td>
        <td class="text-center"><%= button_to 'Delete', enrollment_path(enrollment), method: :delete, data: {confirm: "Are you sure?"} , class: "delete"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-dark voltar"><%= link_to 'Criar um nova Matrícula', new_enrollment_path %></button>

app/views/enrollments/new.html.erb
<h1 class="center bd-danger">Matrícula</h1>
<%= render 'form', enrollment: @enrollment %>

app/views/enrollments/show.html.erb
<div class="container" >
      <div class="pt-10 mx-auto align-middle shadow show" style="width: 500px;">
        <h1 class="mb-5 ">Dados do Matrícula</h1>
        <section class="grid">
          <div><p class="var">Valor Total:</p></div>
          <div><p class="info"><%= @enrollment.total_course_fee %></p></div>
          <div><p class="var">Número de parcelas</p></div>
          <div><p class="info">  <%= @enrollment.number_invoice %></p></div>
          <div><p class="var">Data de Vencimento:</p></div>
          <div><p class="info"><%= @enrollment.expiration_day %></p></div>
          <div><p class="var">Nome do Curso:</p></div>
          <div><p class="info"><%= @enrollment.name_course %></p></div>
          <div><p class="var">Nome do Estudante:</p></div>
          <div><p class="info"><%= @enrollment.student.name %></p></div>
           <div><p class="var">Nome da Instituição:</p></div>
          <div><p class="info"><%= @enrollment.instituion.name %></p></div>
        </section>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Editar', edit_enrollment_path(@enrollment) %></button>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Voltar', enrollments_path %></button>
      </div>
      <table class="table table-striped mx-auto w-75 table-active border border-dark pt-10" >
  <thead>
    <tr class="dark">
      <th class="text-center">Valor</th>
      <th class="text-center">Data de Vencimento</th>
      <th class="text-center">Status</th>
    </tr>
  </thead>

  <tbody>
    <% @enrollment.invoices.each do |invoice| %>
      <tr>
        <td class="text-center"><%= invoice.invoice_amount %></td>
        <td class="text-center"><%= invoice.due_data %></td>
        <td class="text-center"><%= invoice.status %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="fantasma">
</div>