config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :enrollments
  resources :instituions
  resources :students


  get 'students/', to: "posts#index"
  root to: "students#index"


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/instituion.rb
class Instituion < ApplicationRecord
    has_many :enrollments, dependent: :destroy
    
    validates :name,:cnpj, presence: true
    validates :name,:cnpj, uniqueness: true 
    validates :cnpj, length: {is: 11}, numericality: {only_integer: true}
    validates :type_status, inclusion: { in: %w(Universidade Escola Creche),
        message: "Entrada não aceita" }
        
end

app/controllers/instituions_controller.rb
class InstituionsController < ApplicationController
  before_action :set_instituion, only: %i[ show edit update destroy delete]

  # GET /students or /students.json
  def index
    @instituions = Instituion.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @instituion = Instituion.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @instituion = Instituion.new(instituion_params)

    respond_to do |format|
      if @instituion.save
        format.html { redirect_to instituions_path, notice: "Instituion was successfully created." }
        format.json { render :show, status: :created, location: @instituion }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @instituion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    if @instituion.update(instituion_params)
      respond_to do |format|
        format.html { redirect_to instituions_path, notice: 'Instituion was successfully destroyed.' }
      end
    else
      render json: @instituion.errors, status: 422
    end
  end


  # DELETE /students/1 or /students/1.json

  def destroy
    @instituion.destroy
    respond_to do |format|
      format.html { redirect_to instituions_path, notice: 'Instituion was successfully destroyed.' }
      format.json { head :no_content }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instituion
      @instituion = Instituion.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def instituion_params
      params.require(:instituion).permit(:name, :cnpj, :type_status)
    end
end

app/helpers/instituions_helper.rb
module InstituionsHelper
end

app/views/instituions/_form.html.erb
<%= form_with(model: instituion) do |form| %>
  <% if instituion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instituion.errors.count, "error") %> prohibited this instituion from being saved:</h2>

      <ul>
        <% instituion.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%= @instituion.errors.full_messages.first if @instituion.errors.any? %>
    <div class="d-flex justify-content-center row g-3">
      <div class="col-md-7 col-lg-8">
      <div class="form-check col-12">
            <label class="form-label">Nome:</label>
        <%= form.text_field :name  ,class:"form-control"%><br>
      </div>

        <div class="form-check col-12">
            <label class="form-label">CNPJ:</label>
            <%= form.text_field :cnpj  ,class:"form-control"%><br>
        </div>

    <div class="row g-3">
      <div class="form-check col-md-4">
              <label class="form-label">Tipo de instituição:</label>
              <br>
                 <%= form.select :type_status , ['Creche', 'Escola','Universidade'], class:"input-mini"%>
      </div>
      </div>
            <%= form.submit "Enviar" , class:"btn btn-dark enviar actions"%>
        <% end %>
    
    </div>
</div>

 

app/views/instituions/edit.html.erb
<h1 class="center bd-danger">Editar Instituição</h1>
<%= render 'form', instituion: @instituion %>

app/views/instituions/index.html.erb
<h1 class="text-center mt-5 mb-5">Instituição</h1>

<table class="table table-striped mx-auto w-75 table-active border border-dark" >
  <thead>
    <tr class="dark">
      <th class="text-center">Nome</th>
      <th class="text-center">CNPJ</th>
      <th class="text-center">Instituição</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instituions.each do |instituion| %>
      <tr>
        <td class="text-center"><%= instituion.name %></td>
        <td class="text-center"><%= instituion.cnpj %></td>
        <td class="text-center"><%= instituion.type_status %></td>
        <td class="text-center"><%= link_to 'Show', instituion %></td>
        <td class="text-center"><%= link_to 'Edit', edit_instituion_path(instituion) %></td>
        <td class="text-center"><%= button_to 'Delete', instituion_path(instituion), method: :delete, data: {confirm: "Are you sure?"} , class: "delete"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-dark voltar"><%= link_to 'Criar uma nova Instituição', new_instituion_path %></button>

app/views/instituions/new.html.erb
<h1 class="center">Nova Instituição</h1>

<%= render 'form', instituion: @instituion %>

app/views/instituions/show.html.erb
<div class="container" >
      <div class="pt-10 mx-auto align-middle shadow show" style="width: 500px;">
        <h1 class="mb-5 ">Dados do Aluno</h1>
        <section class="grid">
          <div><p class="var">Name:</p></div>
          <div><p class="info"><%= @instituion.name %></p></div>
          <div><p class="var">CNPJ:</p></div>
          <div><p class="info"><%= @instituion.cnpj %></p></div>
          <div><p class="var">Instituição:</p></div>
          <div><p class="info"><%= @instituion.type_status %></p></div>
        </section>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Editar', edit_instituion_path(@instituion) %></button>
        <button type="button" class="btn btn-dark voltar my-5"><%= link_to 'Voltar', instituions_path %></button>
      </div>
</div>